name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1' #Your Flutter Version Here

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      # Optional: Add more steps like building APKs/App Bundles