name: Staging CI/CD

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Add steps to deploy to your staging environment (e.g., Firebase, AWS, etc.)
      # Example for deploying to Firebase:
      - name: Deploy to Firebase (Staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}' # Configure this secret in your repository settings
          projectId: your-staging-project-id
          channelId: live # Or a different channel for staging
          target: staging # Optional: Use a specific target if you have multiple Firebase targets